AlquilaPistas/urls.py
# from alquila_pistas.views import simple_mail, message_mail
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alquila_pistas.urls')),
    # path('email/', simple_mail),
    # path('message', message_mail),
    path('register/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alquila_pistas/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views
from .views import UserProfileView, CourtDetailView

app_name = 'alquila_pistas'

urlpatterns = [

    #Ruta para la vista Principal
    path('', views.IndexView.as_view(), name='IndexView'),
    #Ruta para Crear un Grupo
    path('create-group/', views.CreateGroupView.as_view(), name='create_group'),
    #Ruta para la vista de Sobre Nosotros
    path('about-us/', views.AboutView.as_view(), name='AboutView'),
    #Ruta para la vista de Perfil
    path('profile/', UserProfileView.as_view(), name='profile'),
    #Ruta para actualizar la foto del Perfil
    path('update-profile-image/', views.UpdateProfileImageView.as_view(), name='update_profile_image'),
    #Ruta para la vista de Contacto
    path('contact/', views.ContactView.as_view(), name='ContactView'),
    #Ruta para la vista de Unirse a un Grupo
    path('join-group/', views.JoinGroupView.as_view(), name='JoinGroup'),
    #Ruta para la vista de que te has unido a un grupo correctamente
    path('join-group-success/', views.JoinGroupSuccessView.as_view(), name='JoinGroupSuccessView'),
    #Ruta para la vista de eliminar un grupo
    path('delete-group/', views.DeleteGroupView.as_view(), name='DeleteGroupView'),
    #Ruta para la vista de las pistas de Pabellón
    path('sports-pavilion_court/', views.SportsPavilionCourtView.as_view(), name='SportsPavilionCourtView'),
    #Ruta para la vista de las pistas de Playa
    path('beach-court/', views.BeachCourtView.as_view(), name='BeachCourtView'),
    #Ruta para la vista de detalle de una pista
    path('courts/<int:pk>/', CourtDetailView.as_view(), name='court_detail'),
    #Ruta para el login, logout y registro
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

alquila_pistas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from alquila_pistas.models import *

User = get_user_model()

"""
    Formulario para crear un grupo y opcionalmente hacer una reserva al mismo tiempo.
    Incluye campos adicionales para permitir al usuario unirse automáticamente al grupo
    y proporcionar detalles para realizar una reserva si lo desea.
    
"""
class GroupForm(forms.ModelForm):

    make_reservation = forms.BooleanField(
        required=False,
        label='¿Quieres hacer una reserva?',
        widget=forms.CheckboxInput(attrs={'class': 'reservation-toggle'})
    )

    reservation_name = forms.CharField(
        max_length=100,
        required=False,
    )

    date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'}),

    )

    start_time = forms.TimeField(
        required=False,
        widget=forms.TimeInput(attrs={'type': 'time'}),

    )
    finish_time = forms.TimeField(
        required=False,
        widget=forms.TimeInput(attrs={'type': 'time'}),
    )

    # Define los campos del modelo Group que se utilizaran en el formulario
    class Meta:
        model = Group
        fields = ['name', 'court']
        labels = {
            'name': 'Nombre del grupo',
            'court': 'Pista',
        }

    """
        Valida que si el usuario desea hacer una reserva ('make_reservation' activado),
        entonces todos los campos relacionados con la reserva deben ser completados.
    """
    def clean(self):
        cleaned_data = super().clean()
        make_reservation = cleaned_data.get('make_reservation')

        if make_reservation:
            required_fields = ['court', 'reservation_name', 'date', 'start_time']
            for field in required_fields:
                if not cleaned_data.get(field):
                    self.add_error(field, f'Este campo es requerido si deseas hacer una reserva')

        return cleaned_data


"""
    Formulario de contacto que permite a los usuarios enviar su nombre, email y mensaje.
    Se usa típicamente en la sección de contacto del sitio web.
"""
class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'nombreInput'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'id': 'emailInput'})
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'mensajeTextarea'})
    )

"""
    Formulario personalizado para el registro de nuevos usuarios.
    Extiende el formulario estándar de creación de usuarios de Django e incluye el campo de email.
"""
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    error_messages = {
        "password_mismatch": "Las contraseñas no coinciden, por favor intentelo de nuevo",
    }
    class Meta:
        model = User
        fields = ("username","email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

alquila_pistas/views.py
from email.message import EmailMessage
from django.contrib import messages
from django.contrib.auth import login
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, FormView, ListView
from alquila_pistas.forms import CustomUserCreationForm, GroupForm
from alquila_pistas.models import *
from django.views.generic import TemplateView
from django.core.mail import EmailMessage
from django.shortcuts import redirect, render
from django.urls import reverse
from .forms import ContactForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView



# Create your views here.

"""
    Vista principal donde estará todo el contenido principal de la página.
    Muestra la página de inicio con contenido accesible solo para usuarios autenticados.
"""
class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'alquila_pistas/index.html'



"""
    Vista para crear un grupo.
    Permite a un usuario autenticado crear un grupo y asignarse como creador.
    Opcionalmente, permite hacer una reserva asociada al grupo si el formulario lo indica.
"""
class CreateGroupView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'alquila_pistas/create_group.html'
    success_url = reverse_lazy('alquila_pistas:JoinGroup')

    def form_valid(self, form):
        group = form.save(commit=False)
        # Convertir el usuario lazy a una instancia real de User
        group.creator = User.objects.get(id=self.request.user.id)
        group.save()

        if form.cleaned_data.get('make_reservation'):

            reservation = Reservation(
                court=form.cleaned_data['court'],
                date=form.cleaned_data['date'],
                start_time=form.cleaned_data['start_time'],
                finish_time=form.cleaned_data['finish_time'],
                name_reservation=form.cleaned_data['reservation_name'],
                user=User.objects.get(id=self.request.user.id),
                group=group
            )
            reservation.save()

        return super().form_valid(form)

"""
    Vista que muestra información 'Sobre nosotros'.
    Presenta detalles sobre la empresa o proyecto en una página estática.
"""
class AboutView(LoginRequiredMixin, TemplateView):
    template_name = 'alquila_pistas/about_us.html'

"""
    Vista para enviar mensajes de contacto.
    Permite a usuarios autenticados enviar un formulario de contacto.
    Envía un email al administrador y muestra mensajes de éxito o error.
"""
class ContactView(LoginRequiredMixin, TemplateView):
    template_name = 'alquila_pistas/contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ContactForm()
        return context

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            email_message = EmailMessage(
                'Mensaje de contacto recibido',
                f'Mensaje enviado por {name} <{email}>\n\n{message}',
                email,
                ['d0370296d4-16a4b8@inbox.mailtrap.io'],
                reply_to=[email],
            )

            try:
                email_message.send()
                return redirect(reverse('alquila_pistas:ContactView') + '?ok')
            except:
                return redirect(reverse('alquila_pistas:ContactView') + '?error')

        return self.render_to_response(self.get_context_data(form=form))


"""
    Vista para unirse a grupos existentes.
    Muestra una lista de todos los grupos disponibles con sus datos relacionados.
    Facilita al usuario elegir y unirse a un grupo.
"""
class JoinGroupView(LoginRequiredMixin, ListView):
    model = Group
    template_name = 'alquila_pistas/join_group.html'
    context_object_name = 'groups'

    def get_queryset(self):
        # Optimizamos la carga de datos relacionados
        return Group.objects.select_related('court', 'reservation').prefetch_related('users').all()


"""
    Vista informativa para las pistas del pabellón deportivo.
    Muestra detalles o imágenes de estas pistas para el usuario.
"""
class SportsPavilionCourtView(LoginRequiredMixin, TemplateView):
    template_name = 'alquila_pistas/sports_pavilion_court.html'


"""
    Vista informativa para las pistas de playa.
    Muestra detalles o imágenes de estas pistas para el usuario.
"""
class BeachCourtView(LoginRequiredMixin, TemplateView):
    template_name = 'alquila_pistas/beach_court.html'


"""
    Vista para registrar nuevos usuarios.
    Muestra el formulario de registro y, tras crear el usuario, inicia sesión automáticamente.
"""
class RegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


"""
    Vista que confirma que un usuario se ha unido con éxito a un grupo.
    Añade al usuario a la lista de miembros del grupo seleccionado y muestra mensaje de éxito o error.
"""


class JoinGroupSuccessView(LoginRequiredMixin, TemplateView):
    model = Group
    template_name = 'alquila_pistas/joinGroupSuccess.html'

    def post(self, request, *args, **kwargs):
        group_id = request.POST.get('group_id')
        try:
            group = Group.objects.get(id=group_id)

            # Verificar si el usuario ya está en el grupo
            if request.user in group.users.all():
                messages.error(request, "Ya eres miembro de este grupo")
                return redirect('alquila_pistas:JoinGroup')

            # Verificar si el grupo ya tiene 12 personas
            if group.users.count() >= 12:
                messages.error(request, "El grupo ya ha alcanzado el límite máximo de 12 personas")
                return redirect('alquila_pistas:JoinGroup')

            # Si esta bien, añadimos el usuario
            group.users.add(request.user)
            messages.success(request, "Te has unido al grupo exitosamente")
            return redirect('alquila_pistas:JoinGroupSuccessView')

        except Group.DoesNotExist:
            messages.error(request, "El grupo no existe")
            return redirect('alquila_pistas:JoinGroup')

"""
    Vista para eliminar grupos.
    Primero muestra una página para confirmar la eliminación.
    Solo permite eliminar el grupo si el usuario pertenece a él.
"""
class DeleteGroupView(LoginRequiredMixin, TemplateView):
    template_name = 'alquila_pistas/delete_group.html'

    def get(self, request, *args, **kwargs):
        group_id = request.GET.get('group_id')
        try:
            group = Group.objects.get(id=group_id)
            return render(request, self.template_name, {'group': group})
        except Group.DoesNotExist:
            messages.error(request, "El grupo no existe")
            return redirect('alquila_pistas:IndexView')

    def post(self, request, *args, **kwargs):
        group_id = request.POST.get('group_id')
        try:
            reservation = Reservation.objects.get(group=group_id)
            group = Group.objects.get(id=group_id)
            if request.user.username in [user.username for user in group.users.all()]:
                group_name = group.name
                group.delete()
                reservation.delete()
                messages.success(request, f'El grupo "{group_name}" ha sido eliminado correctamente')

            else:
                messages.error(request, "No tienes permiso para eliminar este grupo")
        except Group.DoesNotExist:
            messages.error(request, "El grupo no existe")

        return redirect('alquila_pistas:IndexView')


"""
    Vista que muestra el perfil del usuario autenticado.
    Incluye la información personal y las reservas hechas por el usuario.
"""
class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'alquila_pistas/profile.html'
    context_object_name = 'profile_user'

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Manejo seguro de las reservas
        try:
            # Intenta obtener las reservas
            reservations = Reservation.objects.filter(user=self.request.user)
            context['reservations'] = reservations
            context['error_message'] = None
        except Exception as e:
            # Si hay un error, establece una lista vacía y guarda el mensaje de error
            print(f"Error al obtener reservas: {str(e)}")
            context['reservations'] = []
            context['error_message'] = "No se pudieron cargar las reservas en este momento."

        return context


"""
    Vista para actualizar la imagen de perfil del usuario vía AJAX.
    Recibe una imagen en la petición POST y la guarda, eliminando la anterior si existe.
    Retorna JSON con el resultado (éxito o error).
"""
@method_decorator(csrf_exempt, name='dispatch')
class UpdateProfileImageView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({
                'success': False,
                'error': 'Usuario no autenticado'
            }, status=401)

        if not request.FILES.get('profile_image'):
            return JsonResponse({
                'success': False,
                'error': 'No se proporcionó ninguna imagen'
            }, status=400)

        try:

alquila_pistas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>{% block title %}AlquilaPistas{% endblock %}</title>
    {% block links %}{% endblock %}
</head>
<body class="d-flex flex-column min-vh-100" style="background-image: url('{% static 'img/foto1.jpeg' %}'); background-size:cover ; background-repeat: no-repeat; background-position: center;background-attachment: fixed; min-height: 100vh; padding-top: 70px;">
    {% include 'header.html' %}
    <div class="container-fluid flex-grow-1 text-white">
        {% block content %}{% endblock %}
    </div>
    {% include 'footer.html' %}
{% block scripts %}
<script src="{% static 'js/javascript.js' %}"></script>
{% endblock %}
</body>
</html>

alquila_pistas/templates/footer.html
{% load static %}
<footer class="py-2 text-black bg-dark navbar-dark">
    <div class="container content text-center">
        <ul class="list-unstyled text-center justify-content-center border-bottom pb-3 mb-3">
            <li>
                <p class="display-6 text-white">Realizado por:</p>
            </li>
            <li>
                <p class="text-white">Alejandro Jiménez Pérez</p>
            </li>
        </ul>
        <p class="text-center text-white">© 2025 AlquilaPistas, Inc</p>
        <a href="https://x.com/?lang=es"><i class="bi bi-twitter-x"></i></a>
        <a href="https://www.instagram.com/"><i class="bi bi-instagram"></i></a>
        <a href="https://es.linkedin.com/"><i class="bi bi-linkedin"></i></a>
        <a href="https://github.com/"><i class="bi bi-github"></i></a>
    </div>
</footer>

alquila_pistas/templates/header.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top shadow">
    <div class="container-fluid">

        <!-- Logo a la izquierda, en negrita y más visible -->
        <a class="navbar-brand fw-bold text-uppercase" href="{% url 'alquila_pistas:IndexView' %}">
            <img src="../static/img/logo.png" width="50px" height="50px" class="rounded-circle bg-white"
                 alt="">
        </a>
        <a class="navbar-brand fw-bold text-uppercase ms-2"
           href="{% url 'alquila_pistas:IndexView' %}">AlquilaPistas</a>

        <!-- Botón para responsive -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Enlaces alineados a la derecha -->
        <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
            <ul class="navbar-nav align-items-center gap-2">

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        Alquiler de Pistas
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark">
                        <li><a class="dropdown-item" href="{% url 'alquila_pistas:create_group' %}">Crear grupo</a></li>
                        <li><a class="dropdown-item" href="{% url 'alquila_pistas:JoinGroup' %}">Unirse a un grupo</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'alquila_pistas:SportsPavilionCourtView' %}">Pistas de
                            Pabellón</a></li>
                        <li><a class="dropdown-item" href="{% url 'alquila_pistas:BeachCourtView' %}">Pistas de
                            playa</a></li>
                    </ul>
                </li>

                <!-- Otros enlaces -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'alquila_pistas:AboutView' %}">Sobre Nosotros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'alquila_pistas:ContactView' %}">Contáctanos</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user"></i> {{ user.username }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'alquila_pistas:profile' %}">
                                    <i class="fas fa-user-circle"></i> Mi Perfil
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <div class="text-start">
                                    <form method="post" action="{% url 'alquila_pistas:logout' %}">
                                        {% csrf_token %}
                                        <input type="submit" value="Cerrar sesión" class="btn">
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>